config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('editthesite/', admin.site.urls),
    path('', include("mainapp.urls", namespace="mainapp"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from mainapp import views
from mainapp.apps import MainappConfig

# app_name = MainappConfig.name

from mainapp.views import ProjectDetailView

app_name = 'mainapp'

urlpatterns = [
    path("", views.MainPageView.as_view(),
         name="mainapp_view"),
    path("contacts/", views.ContactsPageView.as_view(),
         name="mainapp_contacts"),
    path("projects/", views.ProjectPageView.as_view(),
         name="mainapp_projects"),
    path("project/<int:pk>", ProjectDetailView.as_view(),
         name="mainapp_project-detail"),
    path("about/", views.AboutView.as_view(),
         name="mainapp_about"),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

authapp/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from authapp.managers import CustomUserManager


# Create your models here.


class CustomUser(AbstractUser):
    username = None
    email = models.EmailField(unique=True, null=False, blank=False,
                              verbose_name="Почта")
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"

mainapp/models.py
from io import BytesIO

from PIL import Image
from django.core.files.base import ContentFile
from django.db import models


# Create your models here.


class Project(models.Model):
    CATEGORY_CHOICES = [
        ('industry', 'Промышленность'),
        ('logistics', 'Логистика'),
        ('warehouses', 'Склады'),
        ('public-objects', 'Общественные объекты'),
        ('other', 'Другие')]

    name = models.CharField(max_length=256,
                            verbose_name="Наименование проекта")

    title = models.CharField(max_length=256,
                             null=False,
                             blank=False,
                             verbose_name="Заголовок")

    client = models.CharField(max_length=256,
                              null=True,
                              blank=True,
                              verbose_name='Заказчик')

    category = models.CharField(max_length=50,
                                choices=CATEGORY_CHOICES,
                                default='industry',
                                verbose_name='Категория')

    date = models.DateField(
        verbose_name="Дата проекта")

    area = models.IntegerField(
        verbose_name='Площадь', null=True
    )

    description = models.TextField(verbose_name='Описание')

    class Meta:
        verbose_name = 'Проект'
        verbose_name_plural = 'Проекты'

    def __str__(self):
        return self.title


class ProjectImage(models.Model):
    project = models.ForeignKey(Project,
                                on_delete=models.CASCADE,
                                related_name='images')

    image = models.ImageField(upload_to='projects/images/')

    hero_carousel = models.BooleanField(default=False,
                                       verbose_name="Карусель главной страницы")

    def convert_to_webp(self, uploaded_image):
        image = Image.open(uploaded_image)
        image_io = BytesIO()
        image.save(image_io, format='WEBP', quality=80)
        webp_image = ContentFile(image_io.getvalue(), name=uploaded_image.name.split('.')[0] + '.webp')
        return webp_image

    def save(self, *args, **kwargs):
        if self.image:
            self.image = self.convert_to_webp(self.image)
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'Изображение'
        verbose_name_plural = 'Изображения'

    def __str__(self):
        return f'Image for {self.project.title}'

mainapp/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(max_length=100, required=True, label="Ваше Имя")
    email = forms.EmailField(required=True, label="Ваша почта")
    subject = forms.CharField(max_length=100, required=True, label="Тема")
    message = forms.CharField(widget=forms.Textarea, required=True, label="Сообщение")

authapp/views.py
from django.shortcuts import render

# Create your views here.

mainapp/views.py
import logging

from django.contrib import messages
from django.core.mail import send_mail
from django.shortcuts import redirect
from django.urls import reverse
from django.views.defaults import page_not_found
from django.views.generic import TemplateView, ListView, DetailView

from config.settings import DEBUG
from .models import Project
from .forms import ContactForm




class MainPageView(TemplateView):
    template_name = "mainapp/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Профгрупп"
        return context


class ProjectPageView(ListView):
    template_name = 'mainapp/projects.html'
    model = Project
    context_object_name = 'projects'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Проекты'
        context['categories'] = Project.CATEGORY_CHOICES
        return context


class ContactsPageView(TemplateView):
    template_name = "mainapp/contacts.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Контакты"
        context["form"] = ContactForm()

        return context

    def post(self, request, *args, **kwargs):

        form = ContactForm(request.POST)

        if form.is_valid():

            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']
            full_message = f'Сообщение от {name} <{email}\n\n{message}>'

            send_mail(
                subject,
                full_message,
                'murdoc-94@yandex.ru',
                [email],
                fail_silently=False
            )
            messages.success(request, 'Ваше сообщение отправлено')

            return redirect(reverse('mainapp:mainapp_contacts'))

        return redirect(reverse('mainapp:mainapp_contacts'))

      
class ProjectDetailView(DetailView):
    model = Project
    template_name = 'mainapp/project-detail.html'
    context_object_name = 'project'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = self.object.title
        return context


class AboutView(TemplateView):
    template_name = 'mainapp/about.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'О нас'
        return context

def handler404(request, *args, **kwargs):
    if DEBUG:
        return page_not_found()
    return redirect("authapp:main")

mainapp/templates/mainapp/about.html
{% extends "mainapp/includes/base.html" %}
{% load static %}
{% block content %}
  <main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <div class="breadcrumbs d-flex align-items-center" style="background-image: url({% static 'assets/img/breadcrumbs-bg.webp' %});">
      <div class="container position-relative d-flex flex-column align-items-center" data-aos="fade">

        <h2>О нас</h2>
        <ol>
          <li><a href="{% url 'mainapp:mainapp_view' %}">Главная</a></li>
          <li>О нас</li>
        </ol>

      </div>
    </div><!-- End Breadcrumbs -->

    <!-- ======= About Section ======= -->
    <section id="about" class="about">
      <div class="container" data-aos="fade-up">

        <div class="row position-relative">

          <div class="col-lg-7 about-img"
            style="background-image: url({% static 'assets/img/architect-making-plan-with-loupe.webp' %})">
          </div>

          <div class="col-lg-7">
            <h4>

            </h4>
            <div class="our-story">

              <h3>О нас</h3>
              <p style="text-align: justify;">Компания ООО "ПрофГрупп" начала деятельность в 2008 году, за время работы
                мы сформировали небольшую, но профессиональную команду единомышленников, способных решать любые
                поставленные задачи.
                С 2008 года реализовано более 50 объектов, сложность объектов возросла от небольших
                холодных складов - до полноценных cпортивных комплексов и производственных зданий. За данный период
                спроектировано более 1 500 000 кв.м объектов, накоплен огромный ​​опыт проектирования различных
                промышленных и гражданских объектов.</p>
              <ul>
                <li><i class="bi bi-check-circle"></i> <span>Промышленные объекты</span></li>
                <li><i class="bi bi-check-circle"></i> <span>Логистические комплексы</span></li>
                <li><i class="bi bi-check-circle"></i> <span>Складские комплексы</span></li>
                <li><i class="bi bi-check-circle"></i> <span>Гражданские объекты</span></li>
              </ul>
              <p>Наша Миссия - ​​​Проектировать промышленные объекты мирового уровня для будущего России</p>


            </div>
          </div>

        </div>

      </div>
    </section>
    <!-- End About Section -->

    <!-- ======= Stats Counter Section ======= -->
    <section id="stats-counter" class="stats-counter section-bg">
      <div class="container">

        <div class="row gy-4">

          <div class="col-lg-3 col-md-6">
            <div class="stats-item d-flex align-items-center w-100 h-100">
              <i class="bi bi-calendar color-blue flex-shrink-0"></i>
              <div>
                <span data-purecounter-start="0" data-purecounter-end="16" data-purecounter-duration="1"
                  class="purecounter"></span>
                <p>лет работы</p>
              </div>
            </div>
          </div><!-- End Stats Item -->

          <div class="col-lg-3 col-md-6">
            <div class="stats-item d-flex align-items-center w-100 h-100">
              <i class="bi bi-buildings color-orange flex-shrink-0"></i>
              <div>
                <span data-purecounter-start="0" data-purecounter-end="1500000" data-purecounter-duration="1"
                  class="purecounter"></span>
                <p>кв.м спроектировано</p>
              </div>
            </div>
          </div><!-- End Stats Item -->

          <div class="col-lg-3 col-md-6">
            <div class="stats-item d-flex align-items-center w-100 h-100">
              <i class="bi bi-buildings-fill color-green flex-shrink-0"></i>
              <div>
                <span data-purecounter-start="0" data-purecounter-end="1000000" data-purecounter-duration="1"
                  class="purecounter"></span>
                <p>кв.м построено</p>
              </div>
            </div>
          </div><!-- End Stats Item -->


          <div class="col-lg-3 col-md-6">
            <div class="stats-item d-flex align-items-center w-100 h-100">
              <i class="bi bi-buildings-fill color-green flex-shrink-0"></i>
              <div>
                <span data-purecounter-start="0" data-purecounter-end="70" data-purecounter-duration="1"
                  class="purecounter"></span>
                <p>объектов реализовано</p>
              </div>
            </div>
          </div><!-- End Stats Item -->


        </div>

      </div>
    </section><!-- End Stats Counter Section -->

    <!-- ======= Alt Services Section ======= -->
    <section id="alt-services" class="alt-services">
      <div class="container" data-aos="fade-up">

        <div class="row justify-content-around gy-4">
          <div class="col-lg-6 img-bg"
            style="background-image: url({% static 'assets/img/close-up-construction-engineer-holding-plans-hands.webp' %})"
            data-aos="zoom-in" data-aos-delay="100"></div>

          <div class="col-lg-5 d-flex flex-column justify-content-center">
            <h3>Мы работаем и как генпроектировщики и как субподрядчики</h3>
            <p style="text-align: justify;">Используя наш опыт, мы готовы проработать любые стадии
              проектирования
              (от концепций развития территорий, до рабочей документации). Зачастую, к нам обращаются для разработки
              рабочей документации, проанализировав стадию "Проект" мы предлагаем решения по уменьщению капитальных
              затрат (с корректировкой и прохождением повторной экспертизы).</p>

            <div>
              <li><i class="bi bi-check-circle"></i> <span>Раздел 1 "Пояснительная записка"</span></li>
              <li><i class="bi bi-check-circle"></i> <span>Раздел 2 "Схема планировочной организации земельного
                  участка"</span></li>
              <li><i class="bi bi-check-circle"></i> <span>Раздел 3 "Объемно-планировочные и архитектурные
                  решения"</span></li>
              <li><i class="bi bi-check-circle"></i> <span>Раздел 4 "Конструктивные решения"</span></li>
              <li><i class="bi bi-check-circle"></i> <span>Раздел 5 "Сведения об инженерном оборудовании, о сетях и
                  системах инженерно-технического обеспечения"; </span></li>
              <li><i class="bi bi-check-circle"></i> <span>Раздел 6 "Технологические решения"</span></li>
              <li><i class="bi bi-check-circle"></i> <span>Раздел 7 "Проект организации строительства"</span></li>
              <li><i class="bi bi-check-circle"></i> <span>Раздел 11 "Мероприятия по обеспечению доступа инвалидов к
                  объекту капитального строительства</span></li>
            </div>
          </div><!-- End Icon Box -->


        </div>
      </div><!-- End Icon Box -->


      </div>
      </div>

      </div>
    </section><!-- End Alt Services Section -->

    <!-- ======= Alt Services Section 2 ======= -->
    <section id="alt-services-2" class="alt-services section-bg">
      <div class="container" data-aos="fade-up">

        <div class="row justify-content-around gy-4">
          <div class="col-lg-5 d-flex flex-column justify-content-center">
            <h3>Наши преимущества:</h3>
            <p style="text-align: justify;">Гарантируем реализацию проекта любой сложности в соответствии со всеми
              строительными нормами и требованиями заказчика
            </p>

            <div class="icon-box d-flex position-relative" data-aos="fade-up" data-aos-delay="100">
              <i class="bi bi-forward flex-shrink-0"></i>
              <div>
                <h4><a href="" class="stretched-link">Эффективность</a></h4>
                <p>
                  Минимизация металлоемкости и материалоемкости конструкций. Минимизация стоимости земляных работ</p>
              </div>
            </div><!-- End Icon Box -->

            <div class="icon-box d-flex position-relative" data-aos="fade-up" data-aos-delay="200">
              <i class="bi bi-forward flex-shrink-0"></i>
              <div>
                <h4><a href="" class="stretched-link">Опыт</a></h4>
                <p>
                  Наличие высококвалифицированных специалистов и большой опыт успешной работы позволяют предлагать
                  клиентам наиболее подходящие для каждого конкретного объекта решения, обеспечивая тем самым
                  безупречное качество услуг и оптимальные сроки.</p>
              </div>
            </div><!-- End Icon Box -->

            <div class="icon-box d-flex position-relative" data-aos="fade-up" data-aos-delay="300">
              <i class="bi bi-forward flex-shrink-0"></i>
              <div>
                <h4><a href="" class="stretched-link">Качество</a></h4>
                <p>
                  Мы проектируем лучшие объекты, которые получают сертификат соответсвия экологическим стандартам BREEAM
                  (оценка "Very good"), являются победителями CRE Moscow Awards</p>
              </div>
            </div><!-- End Icon Box -->


          </div>

          <div class="col-lg-6 img-bg" style="background-image: url({% static 'assets/img/construction-silhouette.webp' %})"
            data-aos="zoom-in" data-aos-delay="100"></div>
        </div>

      </div>
    </section><!-- End Alt Services Section 2 -->



  </main><!-- End #main -->
{% endblock %}

mainapp/templates/mainapp/contacts.html
{% extends "mainapp/includes/base.html" %}
{% load static %}


{% block content %}

    <main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <div class="breadcrumbs d-flex align-items-center" style="background-image: url('{% static 'assets/img/breadcrumbs-bg.webp' %}');">
      <div class="container position-relative d-flex flex-column align-items-center" data-aos="fade">

        <h2>Контакты</h2>
        <ol>
          <li><a href="{% url 'mainapp:mainapp_view' %}">Главная</a></li>
          <li>Контакты</li>
        </ol>

      </div>
    </div><!-- End Breadcrumbs -->

    <!-- ======= Contact Section ======= -->
    <section id="contact" class="contact">
      <div class="container" data-aos="fade-up" data-aos-delay="100">

        <div class="row gy-4">
          <div class="col-lg-6">
            <div class="info-item  d-flex flex-column justify-content-center align-items-center">
              <i class="bi bi-map"></i>
              <h3>Наш Адрес</h3>
              <p>123022, Россия, г. Москва, Столярный пер., д.3, корп.1</p>
            </div>
          </div><!-- End Info Item -->

          <div class="col-lg-3 col-md-6">
            <div class="info-item d-flex flex-column justify-content-center align-items-center">
              <i class="bi bi-envelope"></i>
              <h3>Почта</h3>
              <p>profg@yandex.ru</p>
            </div>
          </div><!-- End Info Item -->

          <div class="col-lg-3 col-md-6">
            <div class="info-item  d-flex flex-column justify-content-center align-items-center">
              <i class="bi bi-telephone"></i>
              <h3>Секретариат</h3>
              <p>+7 (495) 609 38 85</p>

            </div>
          </div><!-- End Info Item -->

        </div>

        <div class="row gy-4 mt-1">

          <div class="col-lg-6 ">
              <iframe src="https://yandex.ru/map-widget/v1/?um=constructor%3A31a5747411ca15fe9d9541e0b1bab951bd6376878626429a948d6b9e86f718c8&amp;source=constructor" width="636" height="384" frameborder="0"></iframe>
          </div><!-- End Google Maps -->

          <div class="col-lg-6">
            <form action="{% url 'mainapp:mainapp_contacts' %}" method="post" role="form" class="php-email-form">
                {% csrf_token %}
              <div class="row gy-4">
                <div class="col-lg-6 form-group">
                  <input type="text" name="name" class="form-control" id="name" placeholder="Ваше Имя" required>
                </div>
                <div class="col-lg-6 form-group">
                  <input type="email" class="form-control" name="email" id="email" placeholder="Ваша почта" required>
                </div>
              </div>
              <div class="form-group">
                <input type="text" class="form-control" name="subject" id="subject" placeholder="Тема" required>
              </div>
              <div class="form-group">
                <textarea class="form-control" name="message" rows="5" placeholder="Сообщение" required></textarea>
              </div>
              <div class="my-3">
                <div class="loading">Загрузка</div>
                <div class="error-message"></div>
                <div class="sent-message">Ваше сообщение отправлено!</div>
              </div>
              <div class="text-center"><button type="submit">Отправить сообщение</button></div>
            </form>
          </div><!-- End Contact Form -->

        </div>

      </div>
    </section><!-- End Contact Section -->

  </main><!-- End #main -->

{% endblock %}

mainapp/templates/mainapp/includes/header.html
{% load static %}
<header id="header" class="header d-flex align-items-center">
    <div class="container-fluid container-xl d-flex align-items-center justify-content-between">

      <a href="{% url 'mainapp:mainapp_view' %}" class="logo d-flex align-items-center">
        <!-- Uncomment the line below if you also wish to use an image logo -->
        <img src="{% static 'assets/img/PG_logo.png' %}" alt="">
<!--        <h1>UpConstruction<span>.</span></h1>-->
      </a>

      <i class="mobile-nav-toggle mobile-nav-show bi bi-list"></i>
      <i class="mobile-nav-toggle mobile-nav-hide d-none bi bi-x"></i>
      <nav id="navbar" class="navbar">
        <ul>
          <li><a href="{% url 'mainapp:mainapp_view' %}"
            {% if title == "Главная" %}
                 class = "active"
            {% endif %}>Главная</a></li>
          <li><a href="{% url 'mainapp:mainapp_about' %}"
                  {% if title == "О нас" %}
                 class="active"
                  {% endif %}>О нас</a>
          </li>
          <li><a href="{% url 'mainapp:mainapp_projects' %}"
                  {% if title == "Проекты" %}
                 class="active"
                  {% endif %}>Проекты</a></li>


          <li><a href="{% url 'mainapp:mainapp_contacts' %}"
            {% if title == "Контакты" %}
              class = "active"
            {% endif %}>Контакты</a>
          </li>

        </ul>
      </nav><!-- .navbar -->

    </div>
  </header><!-- End Header -->

mainapp/templates/mainapp/project-detail.html
{% extends "mainapp/includes/base.html" %}
{% load static %}


{% block content %}

    <main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <div class="breadcrumbs d-flex align-items-center" style="background-image: url('{% static 'assets/img/breadcrumbs-bg.webp' %}');">
      <div class="container position-relative d-flex flex-column align-items-center" data-aos="fade">

        <h2>Детали проекта</h2>
        <ol>
          <li><a href="{% url 'mainapp:mainapp_view' %}">Главная</a></li>
          <li>Детали проекта</li>
        </ol>

      </div>
    </div><!-- End Breadcrumbs -->

    <!-- ======= Projet Details Section ======= -->
    <section id="project-details" class="project-details">
      <div class="container" data-aos="fade-up" data-aos-delay="100">

        <div class="position-relative h-100">
          <div class="slides-1 portfolio-details-slider swiper">
            <div class="swiper-wrapper align-items-center">
              {% for image in project.images.all %}
                <div class="swiper-slide">
                <img src="{{ image.image.url }}" alt="">
              </div>
              {% endfor %}
            </div>
            <div class="swiper-pagination"></div>
          </div>
          <div class="swiper-button-prev"></div>
          <div class="swiper-button-next"></div>

        </div>

        <div class="row justify-content-between gy-4 mt-4">

          <div class="col-lg-8">
            <div class="portfolio-description">
              <h2>{{ project.title}}</h2>
              <p>
                  {{ project.description }}
              </p>

            </div>
          </div>

          <div class="col-lg-3">
            <div class="portfolio-info">
              <h3>Информация о проекте</h3>
              <ul>
                <li><strong>Категория</strong> <span>{{ project.get_category_display }}</span></li>
                  {% if project.client %}
                <li><strong>Заказчик</strong> <span>{{ project.client }}</span></li>
                  {% endif %}
                <li><strong>Год</strong> <span>{{ project.date|date:"Y" }}</span></li>
                <li><strong>Площадь</strong> <span>{{ project.area }} м²</span></li>
              </ul>
            </div>
          </div>

        </div>

      </div>
    </section><!-- End Projet Details Section -->


  </main><!-- End #main -->

{% endblock %}

mainapp/templates/mainapp/projects.html
{% extends "mainapp/includes/base.html" %}
{% load static %}


{% block content %}

    <main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <div class="breadcrumbs d-flex align-items-center" style="background-image: url('{% static 'assets/img/breadcrumbs-bg.webp' %}');">
      <div class="container position-relative d-flex flex-column align-items-center" data-aos="fade">

        <h2>Проекты</h2>
        <ol>
          <li><a href="{% url 'mainapp:mainapp_view' %}">Главная</a></li>
          <li>Проекты</li>
        </ol>

      </div>
    </div><!-- End Breadcrumbs -->

    <!-- ======= Our Projects Section ======= -->
    <section id="projects" class="projects">
      <div class="container" data-aos="fade-up">

        <div class="portfolio-isotope" data-portfolio-filter="*" data-portfolio-layout="masonry" data-portfolio-sort="original-order">

          <ul class="portfolio-flters" data-aos="fade-up" data-aos-delay="100">
            <li data-filter="*" class="filter-active">Все</li>
              {% for category in categories %}
                  <li data-filter=".filter-{{ category.0 }}">{{ category.1 }}</li>
              {% endfor %}
          </ul><!-- End Projects Filters -->

          <div class="row gy-4 portfolio-container" data-aos="fade-up" data-aos-delay="200">
            {% for project in projects %}

                <div class="col-lg-4 col-md-6 portfolio-item filter-{{ project.category }}">
              <div class="portfolio-content h-100">
                <img src="{{ project.images.first.image.url }}" class="img-fluid" alt="" style="aspect-ratio: 16 / 10.7">
                <div class="portfolio-info">
                  <h4>{{ project.get_category_display }}</h4>
                  <p>{{ project.title }}</p>
                  <a href="{{ project.images.first.image.url }}" title="{{ project.category}}" data-gallery="portfolio-gallery-{{ project.category }}" class="glightbox preview-link"><i class="bi bi-zoom-in"></i></a>
                  <a href="{% url 'mainapp:mainapp_project-detail' project.pk %}" title="More Details" class="details-link"><i class="bi bi-link-45deg"></i></a>
                </div>
              </div>
            </div><!-- End Projects Item -->

            {% endfor %}
          </div><!-- End Projects Container -->

        </div>

      </div>
    </section><!-- End Our Projects Section -->

  </main><!-- End #main -->

{% endblock %}